export const models = [
  {
    id: "custom-openai",
    name: "Custom OpenAI",
    chef: "Custom",
    chefSlug: "custom",
    providers: ["openai"],
  },
  {
    id: "custom-dify",
    name: "Custom Dify",
    chef: "Custom",
    chefSlug: "dify",
    providers: ["dify"],
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/o1-preview",
    name: "o1 Preview",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/o1-mini",
    name: "o1 Mini",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Claude 3 Opus",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3-sonnet",
    name: "Claude 3 Sonnet",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3.5-haiku",
    name: "Claude 3.5 Haiku",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "google/gemini-2.0-flash-exp:free",
    name: "Gemini 2.0 Flash Exp",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "google/gemini-pro-1.5",
    name: "Gemini 1.5 Pro",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "google/gemini-flash-1.5",
    name: "Gemini 1.5 Flash",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "meta-llama/llama-3.3-70b-instruct",
    name: "Llama 3.3 70B",
    chef: "Meta",
    chefSlug: "llama",
    providers: ["groq", "togetherai", "amazon-bedrock"],
  },
  {
    id: "meta-llama/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B",
    chef: "Meta",
    chefSlug: "llama",
    providers: ["togetherai", "amazon-bedrock"],
  },
  {
    id: "meta-llama/llama-3.1-70b-instruct",
    name: "Llama 3.1 70B",
    chef: "Meta",
    chefSlug: "llama",
    providers: ["groq", "togetherai", "amazon-bedrock"],
  },
  {
    id: "meta-llama/llama-3.1-8b-instruct",
    name: "Llama 3.1 8B",
    chef: "Meta",
    chefSlug: "llama",
    providers: ["groq", "togetherai"],
  },
  {
    id: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    chef: "DeepSeek",
    chefSlug: "deepseek",
    providers: ["deepseek", "openrouter"],
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek V3",
    chef: "DeepSeek",
    chefSlug: "deepseek",
    providers: ["deepseek", "openrouter"],
  },
  {
    id: "deepseek/deepseek-coder",
    name: "DeepSeek Coder V2",
    chef: "DeepSeek",
    chefSlug: "deepseek",
    providers: ["deepseek", "openrouter"],
  },
  {
    id: "mistralai/mistral-large-2411",
    name: "Mistral Large",
    chef: "Mistral AI",
    chefSlug: "mistral",
    providers: ["mistral", "azure"],
  },
  {
    id: "mistralai/mistral-small-24b-instruct-2501",
    name: "Mistral Small",
    chef: "Mistral AI",
    chefSlug: "mistral",
    providers: ["mistral", "azure"],
  },
  {
    id: "mistralai/codestral-2501",
    name: "Codestral",
    chef: "Mistral AI",
    chefSlug: "mistral",
    providers: ["mistral"],
  },
  {
    id: "qwen/qwen-2.5-72b-instruct",
    name: "Qwen 2.5 72B",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba", "openrouter"],
  },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba", "openrouter"],
  },
  {
    id: "qwen/qwen-max",
    name: "Qwen Max",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba"],
  },
  {
    id: "cohere/command-r-plus-08-2024",
    name: "Command R+",
    chef: "Cohere",
    chefSlug: "cohere",
    providers: ["cohere", "azure", "amazon-bedrock"],
  },
  {
    id: "cohere/command-r-08-2024",
    name: "Command R",
    chef: "Cohere",
    chefSlug: "cohere",
    providers: ["cohere", "azure", "amazon-bedrock"],
  },
  {
    id: "x-ai/grok-3",
    name: "Grok 3",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
  {
    id: "x-ai/grok-2-1212",
    name: "Grok 2 1212",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
  {
    id: "x-ai/grok-vision-beta",
    name: "Grok Vision",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
  {
    id: "moonshotai/moonshot-v1-128k",
    name: "Moonshot v1 128K",
    chef: "Moonshot AI",
    chefSlug: "moonshotai",
    providers: ["moonshotai"],
  },
  {
    id: "moonshotai/moonshot-v1-32k",
    name: "Moonshot v1 32K",
    chef: "Moonshot AI",
    chefSlug: "moonshotai",
    providers: ["moonshotai"],
  },
  {
    id: "perplexity/sonar-pro",
    name: "Sonar Pro",
    chef: "Perplexity",
    chefSlug: "perplexity",
    providers: ["perplexity"],
  },
  {
    id: "perplexity/sonar",
    name: "Sonar",
    chef: "Perplexity",
    chefSlug: "perplexity",
    providers: ["perplexity"],
  },
  {
    id: "vercel/v0-chat",
    name: "v0 Chat",
    chef: "Vercel",
    chefSlug: "v0",
    providers: ["vercel"],
  },
  {
    id: "amazon/nova-pro-v1:0",
    name: "Nova Pro",
    chef: "Amazon",
    chefSlug: "amazon-bedrock",
    providers: ["amazon-bedrock"],
  },
  {
    id: "amazon/nova-lite-v1:0",
    name: "Nova Lite",
    chef: "Amazon",
    chefSlug: "amazon-bedrock",
    providers: ["amazon-bedrock"],
  },
  {
    id: "amazon/nova-micro-v1:0",
    name: "Nova Micro",
    chef: "Amazon",
    chefSlug: "amazon-bedrock",
    providers: ["amazon-bedrock"],
  },
];
