export const models = [
  {
    id: "custom-openai",
    name: "Custom OpenAI",
    chef: "Custom",
    chefSlug: "custom",
    providers: ["openai"],
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/o1-preview",
    name: "o1 Preview",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "openai/o1-mini",
    name: "o1 Mini",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["openai", "azure"],
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Claude 3 Opus",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3-sonnet",
    name: "Claude 3 Sonnet",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "anthropic/claude-3.5-haiku",
    name: "Claude 3.5 Haiku",
    chef: "Anthropic",
    chefSlug: "anthropic",
    providers: ["anthropic", "azure", "google-vertex", "amazon-bedrock"],
  },
  {
    id: "google/gemini-2.0-flash-exp:free",
    name: "Gemini 2.0 Flash Exp",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "google/gemini-pro-1.5",
    name: "Gemini 1.5 Pro",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "google/gemini-flash-1.5",
    name: "Gemini 1.5 Flash",
    chef: "Google",
    chefSlug: "google",
    providers: ["google", "google-vertex"],
  },
  {
    id: "qwen/qwen-2.5-72b-instruct",
    name: "Qwen 2.5 72B",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba", "openrouter"],
  },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba", "openrouter"],
  },
  {
    id: "qwen/qwen-max",
    name: "Qwen Max",
    chef: "Alibaba",
    chefSlug: "alibaba",
    providers: ["alibaba"],
  },
  {
    id: "x-ai/grok-3",
    name: "Grok 3",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
  {
    id: "x-ai/grok-2-1212",
    name: "Grok 2 1212",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
  {
    id: "x-ai/grok-vision-beta",
    name: "Grok Vision",
    chef: "xAI",
    chefSlug: "xai",
    providers: ["xai"],
  },
];
